### ISSUE TITLE
Error to import

### ISSUE THREAD

**Issue by joseliko7** [zhuqianqian/Passbook#1]
C:\Users\Jose\Desktop\Passbook-master\app\src\free\res\layout\activity_main.xml
Error:(40, 27) No resource found that matches the given name (at 'adUnitId' with value '@string/admob_ad_unit').
C:\Users\Jose\Desktop\Passbook-master\app\src\free\res\layout-w600dp\activity_main.xml
Error:Execution failed for task ':app:processFreeDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1
> Error:(52, 23) No resource found that matches the given name (at 'adUnitId' with value '@string/admob_ad_unit').

**Comment by zhuqianqian** [comment]
This is expected because the admob unit id is my account specific. If you want to build it on your own, add the missing IDs as non translable string resources, including admob unit id and app id which is used in data synchronization.

I will add a wiki for this, Thank you for pointing it out.

At this time, if you have not got your Admob account ready, you can build pro flavor and add only appid that can be a random number as long as you do not care about the synchronization.

**Comment by joseliko7** [comment]
Thank you? Rather, thanks to you.
Can I remove advertising?

**Comment by zhuqianqian** [comment]
Thank you for pointing this out, i mean i should have added a wiki to explain this. 

Absolutely you can. The easiest way is to select proDebug/proRelease when you build the project, that will use the ads-free version to build.

Still you have to add the a random or valid appid to make the build work though.

**Comment by joseliko7** [comment]
Thanks.
I'm from Spain and I want to help with the Spanish language.Spanish I will send the file to 100 %
Date: Tue, 13 Oct 2015 19:28:25 -0700

**Comment by zhuqianqian** [comment]
Thank you very much! I have awlways wanted to make a Spanish translation...

To translate, you can use this tool https://299studio.oneskyapp.com/collaboration/project?id=39783, However, that tool is not so easy to use, so you can also put directly in the repo and i can move it there.

**Comment by joseliko7** [comment]
Tell me your email , I will send you directly.

**Comment by zhuqianqian** [comment]
Please send it to zhuqianqian. android@gmail.com

Thank you!

**Comment by joseliko7** [comment]
Translation sent successfully.

**Comment by joseliko7** [comment]
I am going to sleep in Spain it is late.
Espero que mañana diario explicando cómo importar jeje

**Comment by zhuqianqian** [comment]
Sorry the email was wrong. There should not be a space after the dot, and it was my IME automatically put it. That is zhuqianqian.android@gmail.com

I suggest you update it via git and i can merge it. In this way you are shown as the contributor.

I am also going to sleep as well since it's midnight in EDT now.

**Comment by joseliko7** [comment]
Ok, Translation sent successfully.

**Comment by joseliko7** [comment]
You can use it anywhere , anytime.
I give you all the freedom of use.

You can use 100% wherever you want.

**Comment by joseliko7** [comment]
How do I remove ads ?
When exporting shows me this error:

C:\Users\Jose\Desktop\Passbook-master\app\src\free\res\layout\activity_main.xml
Error:(40, 27) No resource found that matches the given name (at 'adUnitId' with value '@string/admob_ad_unit').
C:\Users\Jose\Desktop\Passbook-master\app\src\free\res\layout-w600dp\activity_main.xml
Error:(52, 23) No resource found that matches the given name (at 'adUnitId' with value '@string/admob_ad_unit').
Error:Execution failed for task ':app:processFreeDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by zhuqianqian** [comment]
Before you try to build or export, select the paidDebug or paid Release in Android Studio. This will automatically choose the version without ads.

Otherwise you have change all the files under free directory, including AndroidManifest.xml, all layout files and Java source.

**Comment by joseliko7** [comment]
I selected but gives me this error:

Error:(43, 28) No resource found that matches the given name (at 'value' with value '@string/app_id').
C:\Users\Jose\Desktop\Passbook-master\app\build\intermediates\manifests\full\paid\release\AndroidManifest.xml
Error:Execution failed for task ':app:processPaidReleaseResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by zhuqianqian** [comment]
Yes, as I said in the reply I posted yesterday, you have to at least add a fake appid to run the build smoothly. The appid is a Google cloud project appid in order to use the Google play services to synchronize data.

Add a file under main/res/values/, and put the following content in the file, where you should replace XXX with your own project ID or a random number if you don't care about the synchronization right now:

``` xml
<resources>
  <string name="app_id">XXX</string>
</resources>
```

**Comment by joseliko7** [comment]
Send me a sample file please. 
Thanks!

**Comment by zhuqianqian** [comment]
I sent you the example file. I also added a Wiki page for the build instructions
https://github.com/zhuqianqian/Passbook/wiki/Build-Instructions

Thank you again for reporting the issue!
